# Dockerfile.prod

FROM golang:1.21.3 AS builder

WORKDIR /app
ENV GO111MODULE=on

COPY go.mod go.sum ./

RUN go mod download
COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

RUN go build -o main .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

ENV GIN_MODE=release

EXPOSE 8080

CMD ["./main"]
