version: '3.7'

services:
  db:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    command: ['--replSet', '${MONGO_REPLICA_SET_NAME}', '--bind_ip_all']
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - ./db:/data/db
      - ./scripts/set-credentials.sh:/docker-entrypoint-initdb.d/set-credentials.sh

  replica-setup:
    image: mongo
    restart: on-failure
    networks:
      default:
    volumes:
      - ./scripts/setup-replica.sh:/scripts/setup-replica.sh
    entrypoint: ['bash', '/scripts/setup-replica.sh']
    depends_on:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
