version: '3.8'

services:
  mongo_gptv:
    image: mongo
    command: ['--replSet', 'rs0', '--bind_ip_all']
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongodb_data:/data/db
      - ./config/mongo-config:/data/configdb
    networks:
      - mongo-net

  mongosetup:
    image: mongo
    depends_on:
      - mongo_gptv
    volumes:
      - ./database/mongodb/scripts:/scripts
    restart: 'no'
    entrypoint:
      [
        'bash',
        '/scripts/wait-for-it.sh',
        'mongo_gptv:27017',
        '--',
        'bash',
        '/scripts/init.sh',
      ]
    networks:
      - mongo-net

  gptv_backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - 8080:8080
    depends_on:
      - mongo_gptv
      - redis
      - mongosetup
    networks:
      - mongo-net
    env_file:
      - ./config/prod.env

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mongo-net

  nginx:
    context: .
    dockerfile: Dockerfile.nginx.prod
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx-config/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - gptv_backend
    networks:
      - mongo-net

volumes:
  mongodb_data:
  mongodb_config:

networks:
  mongo-net:
