definitions:
  translator.TranslationEntry:
    properties:
      code:
        type: string
      text:
        type: string
    type: object
  translator.TranslationSwaggerResponse:
    properties:
      message:
        $ref: '#/definitions/translator.TranslationEntry'
    type: object
  usermodel.UserDeleteModel:
    properties:
      id:
        type: string
    type: object
  usermodel.UserSwaggerParams:
    properties:
      email:
        example: user@example.com
        type: string
      fullname:
        example: John Doe
        type: string
      name:
        example: johndoe
        type: string
      password:
        example: password123
        type: string
      role:
        example: admin
        type: string
      username:
        example: johndoe
        type: string
    required:
    - email
    - password
    type: object
host: localhost:4141
info:
  contact:
    email: yusufocaliskan@gmail.com
    name: '@yusufocaliskan'
  description: To manage the whole gptv.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GPTVerse Admin Backend
  version: "1.0"
paths:
  /api/v1/user/createByEmail:
    post:
      consumes:
      - application/json
      description: Creates new user
      operationId: create-user
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usermodel.UserSwaggerParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usermodel.UserSwaggerParams'
      summary: New user
  /api/v1/user/deleteById:
    delete:
      consumes:
      - application/json
      description: Deletes a user by given user id
      operationId: Delete-User
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usermodel.UserDeleteModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/translator.TranslationSwaggerResponse'
      security:
      - BearerAuth: []
      summary: Delete user
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
